#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [22]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [23]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10])

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [6]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [9]:
print(arr)
arr[5]=1
print(arr)

[ 0  1  2  3  4  1  6  7  8  9 10]
[ 0  1  2  3  4  1  6  7  8  9 10]


#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [12]:
arr2=np.arange(10,50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [17]:
arr3=np.arange(0,51)
print(arr3)
arr4=arr3[::-1]
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [20]:
arr5=np.arange(0,9)
mat=arr5.reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի ինդեքսները:

In [14]:
arr8=np.array([1,2,0,0,4,0])
x=np.where(arr8==0)
print(x)

(array([2, 3, 5], dtype=int32),)


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [36]:
from numpy import random
arr9=random.randint(20, size=(3,3))
print(arr9)

[[11 12 15]
 [17  8 18]
 [19 16 15]]


#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [47]:
arr10=random.random((10,10))
print(arr10)
max10=arr10.max()
min10=arr10.min()
print (max10)
print (min10)

[[0.95426542 0.07012634 0.0527935  0.12317861 0.84495285 0.18712201
  0.59130397 0.61252005 0.12456114 0.31969988]
 [0.50297062 0.13621725 0.01657517 0.26000156 0.93143634 0.38621392
  0.20955548 0.98905581 0.47430184 0.9601797 ]
 [0.47419973 0.24334503 0.32529367 0.28580104 0.1581203  0.54583674
  0.93307319 0.82278442 0.1199282  0.12107102]
 [0.70752776 0.74094247 0.43797268 0.43787207 0.48319165 0.94400545
  0.63843695 0.50368146 0.86938249 0.74984065]
 [0.72704197 0.86205435 0.94488733 0.62686892 0.17445155 0.3548039
  0.5648636  0.22013914 0.76706377 0.05326639]
 [0.18098096 0.99267998 0.26043753 0.45328293 0.49143931 0.19431501
  0.86656793 0.55526265 0.54937054 0.32275797]
 [0.03022154 0.73962957 0.79824988 0.49071345 0.29750139 0.15965424
  0.47080869 0.81192984 0.48853958 0.64268602]
 [0.10831537 0.59523268 0.15675078 0.5435082  0.29635209 0.37913614
  0.63781832 0.0594704  0.50305902 0.89045098]
 [0.79266795 0.47848524 0.03487734 0.68451345 0.47926235 0.05190516
  0.34946662 

In [51]:
arr11=random.randint(0,100,(10,10))
print(arr11)
max11=arr11.max()
min11=arr11.min()
print (max11)
print (min11)

[[32 77 49 20 67 82  8  3 39 23]
 [22 43 24 87 34 29 18 67 49 50]
 [25 62 56 16 45 62 18 38  0 76]
 [75  6 67 63 91 39 80 80 36 45]
 [29 88 41 44 86 36 14 18 67 63]
 [55 41 69 57 90 61 90  2 10 74]
 [44 31 21 34 29 53 55 39 34 95]
 [81 12 19 31 67 24 80 14 67 58]
 [30 45 94 23 41 30 44 92 60 99]
 [62 33 59 30 67 13 76 94  4 77]]
99
0


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [69]:

arr111=random.randint(100, size=(30))
print(arr111)
arrmean=np.mean(arr11)
print(arrmean)

[56 36 27 76 62 77 93  9 94 76 84 75 32 47 88 83 63 56 80 31 95 49  5 65
 93 56 43 50 45 14]
47.99


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [73]:
arr12=np.arange(0,10)
print(arr12)
arr121=arr12[3:9]
print(arr121)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [143]:
arr13=random.randint(0,10,20)
print(arr13)
arr131=[2*x for x in arr13 if x<5]
print(arr131)
arr1311=np.array(arr131)
print(arr1311)
type(arr1311)
        
        

[8 6 2 7 2 9 4 3 2 6 8 3 7 2 7 7 9 1 2 5]
[4, 4, 8, 6, 4, 6, 4, 2, 4]
[4 4 8 6 4 6 4 2 4]


numpy.ndarray

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [21]:
arr14=np.array([1,5,6,2,-2,23,45])
print(arr14)
arr141=np.where(arr14%2==0)
print(arr141)
print(arr14[arr141])

[ 1  5  6  2 -2 23 45]
(array([2, 3, 4], dtype=int32),)
[ 6  2 -2]


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [91]:
arr15=np.arange(0,21)
print(arr15)
filter_arr15=arr15%3==0
print(filter_arr15)
newarr15=arr15[filter_arr15]
print (newarr15)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False False  True False False  True False False  True False False
  True False False  True False False  True False False]
[ 0  3  6  9 12 15 18]


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [102]:
arr16=np.array([0,1,2,3,4], ndmin=5)
print (arr16)

[[[[[0 1 2 3 4]]]]]


#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [107]:
arr17=np.array([[0, 1],[2, 3]])
print(arr17)
maxarr17=arr17.max()
print("max value is: %s" % maxarr17)
minarr17=arr17.min()
print("min value is: %s" % minarr17)


[[0 1]
 [2 3]]
max value is: 3
min value is: 0


#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [110]:
arr18=np.array([[0, 1],[2, 3]])
print(arr18)
maxarr0=np.amax(arr18,axis=0)
print("max value in each column is: %s" % maxarr0)
minarr0=np.amin(arr18,axis=0)
print("min value in each column is: %s" % minarr0)


[[0 1]
 [2 3]]
max value in each column is: [2 3]
min value in each column is: [0 1]


#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [116]:
arr19=np.array([5,6,9,8,10,7,9,33,100,66])
print(arr19)
meanarr19=np.mean(arr19)
print(meanarr19)
medianarr19=np.median(arr19)
print(medianarr19)
print(sorted(arr19))
print(np.std(arr19))
print(np.var(arr19))

[  5   6   9   8  10   7   9  33 100  66]
25.3
9.0
[5, 6, 7, 8, 9, 9, 10, 33, 66, 100]
30.789771028703672
948.01


#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) using weights np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])` օգտագործելով np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) weight-երը։

In [123]:
arr20=np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])
weight=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr20)
print(np.average(arr20 , weights=[1,2,3,4,5,6,7,8,9,10]))

[ 2  4  3  5  6 12 34  2 34  5]
13.654545454545454


#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [137]:
arr21=np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
print(arr21)
arr211=np.sort(arr21, axis=1)
print(arr211)

[[4 2 6 1]
 [0 2 6 1]
 [4 4 1 9]]
[[1 2 4 6]
 [0 1 2 6]
 [1 4 4 9]]


#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [136]:
a=np.array([[5 , 6 ,7],[5 ,-3 ,0]])
print(a)
b=np.array([[5 , 1],[2 ,1], [3 ,-3]])
print(np.dot(a,b))

[[ 5  6  7]
 [ 5 -3  0]]
[[ 58 -10]
 [ 19   2]]


## Finish